baseURL = "http://sel3-2023-group-01.github.io/"
languageCode = "en-UK"
title = "The Fastest Brittle Star Alive"
theme = "hello-friend-ng"

[params]
    displayTitle = "SEL3 - Group 1"
    homeSubtitle = "Software Engineering Lab 3 (2023)"
    enableThemeToggle = true

    intro = "You definitely know SpongeBob, but do you know about other creatures that live under the sea? Like brittle stars? In this project we're going to help the brittle star become the fastest version of himself. We'll train him in some environments, optimise his morphology and learn him how to control his new body!"

    [[params.social]]
    name = "github"
    url = "https://github.com/sel3-2023-group-01/"
[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            hardWraps = true
