baseURL = "http://sel3-2023-group-01.github.io/"
languageCode = "en-UK"
title = "SEL3 - Group 01"
theme = "hello-friend-ng"

[params]
    homeSubtitle = "Sofware Engineering Lab 3 (2023)"
    enableThemeToggle = true

    [[params.social]]
    name = "github"
    url = "https://github.com/sel3-2023-group-01/"
